-- MySQL Script generated by MySQL Workbench
-- 08/12/16 23:11:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_jcontrolversion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre de la Empresa` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(2000) NULL,
  UNIQUE INDEX `Nombre de la Empresa_UNIQUE` (`Nombre de la Empresa` ASC),
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_sede` (
  `id_sede` INT NOT NULL AUTO_INCREMENT,
  `id_empresa` INT NOT NULL,
  `nombre_sede` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_sede`),
  INDEX `fk_tbl_sede_tbl_empresa1_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_tbl_sede_tbl_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_jcontrolversion`.`tbl_empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `id_sede` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_tbl_usuario_tbl_sede1_idx` (`id_sede` ASC),
  CONSTRAINT `fk_tbl_usuario_tbl_sede1`
    FOREIGN KEY (`id_sede`)
    REFERENCES `db_jcontrolversion`.`tbl_sede` (`id_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `rol_UNIQUE` (`rol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario_rol`),
  INDEX `fk_tbl_usuario_rol_tbl_rol_idx` (`id_rol` ASC),
  INDEX `fk_tbl_usuario_rol_tbl_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_usuario_rol_tbl_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db_jcontrolversion`.`tbl_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_usuario_rol_tbl_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_jcontrolversion`.`tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `permiso` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `permiso_UNIQUE` (`permiso` ASC),
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_rol_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_rol_permisos` (
  `id_rol_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_rol_permiso`),
  INDEX `fk_tbl_rol_permisos_tbl_rol1_idx` (`id_rol` ASC),
  INDEX `fk_tbl_rol_permisos_tbl_permiso1_idx` (`id_permiso` ASC),
  CONSTRAINT `fk_tbl_rol_permisos_tbl_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db_jcontrolversion`.`tbl_rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_rol_permisos_tbl_permiso1`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `db_jcontrolversion`.`tbl_permiso` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_jcontrolversion`.`tbl_log_seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_jcontrolversion`.`tbl_log_seguridad` (
  `id_log_seguridad` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_accion` DATETIME NOT NULL DEFAULT NOW(),
  `accion` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id_log_seguridad`),
  INDEX `fk_tbl_log_seguridad_tbl_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_log_seguridad_tbl_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_jcontrolversion`.`tbl_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
